# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on: # this is the place where we configure at what time actions need to be run, so here we run this action on pushes and pull requests on main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted # at here we are using a shared host to run action, if we setup a self hosteed runner then we can use its name here
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Frontend Compilation (Syntax Check)
      run: cd client && find . -name "*.js" -exec node --check {} +

    - name: Backend Compilation (Syntax Check)
      run: cd api && find . -name "*.js" -exec node --check {} +

  gitleaks-scan:
    runs-on: self-hosted
    needs: compile 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitLeaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1

  trivy_fs_scan:
    runs-on: self-hosted
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trviy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with: 
          scan-type: 'fs'           # "fs" = filesystem scan. Scans the current directory (your source code) for vulnerable dependencies & config issues
          scan-ref: '.'             # '.' = scan the repo root (the code you checked out). You could point this to client/ or api/ if you want to scan only part
          format: 'table'           # Output format → nice human-readable table in the Actions logs (other options: json, sarif, template…)
          ignore-unfixed: true      # Ignores vulnerabilities that don’t have a fix available yet (reduces noise, but you might miss awareness of risks)
          vuln-type: 'os,library'   # Scan both OS packages (like apt-installed things) and libraries (like npm packages in node_modules)
          severity: 'CRITICAL,HIGH' # Only report vulnerabilities at these levels. Ignores MEDIUM/LOW to keep signal-to-noise ratio better
      

      
